### ISSUE TITLE
Double click on hdf5 files does not open HDF5View

### ISSUE THREAD

**Issue by DeveloperPablo** [marts/hdf5view#14]
Hello,

I want to double click my .hdf5 files associated with hdf5view script ("with open with " option) but when i did it, nothing happened.

I followed the instruction to add the script to "registry editor" in w11, with the same result. 

I did not have problem to open the hdf5view.exe alone, but i want a more fast way to open my files, instead ok drag the .hdf5 files to the hdf5view window.

**Comment by tgwoodcock** [comment]
Hi @DeveloperPablo, 

I think there are two different things here. 
- Unfortunately, I don't think it will be possible to associate all hdf5 files with hdf5view so that they open with a double click because hdf5view is not installed under Windows.
- With the method described in the REAMDE to get "open with hdf5view" on the context menu (which you mentioned you have already followed), you should be able to right-click on an hdf5 file, then left-click "open with hdf5view" in the context menu which appears, and hdf5view should then open the file (still with only two clicks). This method works on Windows 10 and 11.

If you're having problems with the right-click, then select "open with hdf5view" from the context menu, it might be worth checking the commands you added to the registry as there may be a typo or something - I know from experience that this can happen easily ;) If you are still having problems, you're welcome to post the commands you added to the registry and I'll take a look and see if I can help.

**Comment by DeveloperPablo** [comment]
I add a key as README said, and add to name=Default, type=REG_SZ, Data=G:\Program Files\Python312\Scripts\hdf5view.exe -f. 

After i tried to "open with hdf5view" and an error occur "The file does not have an app associated with it for performing this action. Please install an app or, if one is already installed, create an association in the Default Apps Settings Page".

**Comment by tgwoodcock** [comment]
That's almost right, you just need to add  `"%1"` to the end of your command so that, in your case, the "Data" part is:

`G:\Program Files\Python312\Scripts\hdf5view.exe -f "%1"`

The last part passes the path of the file you right-click on into the command. Then hdf5view knows which file you want to open. Once you have modified the command, you can right-click on an hdf5 file, select "open with hdf5view" from the context menu and it should work.

**Comment by tgwoodcock** [comment]
Hope the above advice helped. It would be great if you could let me know and then I'll close this issue. Thanks.

**Comment by tgwoodcock** [comment]
The README has now been updated with step-by-step instructions of how to set up and use "Open with hdf5view" on the Windows context menu. This has been tested and works with Windows 10 and 11.

To summarise:
- it is not possible to use a double-click to open HDF5 files with hdf5view
- you can right-click on an HDF5 file and select `Open with hdf5view`, which still opens any HDF5 file in two clicks.
- instructions to set this up in Windows are available in the README. This will be extended to include other OS later.

**Comment by DeveloperPablo** [comment]
Hello,

It actually work with the new README, the difference was to add a new kew "command" and then modify the name in it. Thanks you.

**Comment by tgwoodcock** [comment]
Glad it worked. The instructions are the same as in the old README but more clearly described now, so that's a step forward.
