### ISSUE TITLE
Relative import issues

### ISSUE THREAD

**Issue by jomade** [marts/hdf5view#6]
Hi!

after 
```
pip install -e .
```
running main.py in PyCharm leaves me with the following error message: 

```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "main.py", line 29, in <module>
    from . import __version__
ImportError: attempted relative import with no known parent package
```

Changing to 
``` 
from hdf5view import __version__
from hdf5view.mainwindow import MainWindow
```
resolves it. Are there any concerns in changing it like that? 

Btw: Thanks for a very promising project!

**Comment by tgwoodcock** [comment]
Hi @jomade! Thanks for getting in touch, I'm glad you're enjoying using hdf5view.

Regarding the import issue, we're not really intending that people run main.py to start hdf5view. The usual ways to start the program are either to call

```powershell
hdf5view
````

from the console (e.g. Powershell or Bash), or to create a desktop link to the gui-script, which should be located in your Python/Scripts folder.

I'd prefer to keep the relative imports because then we're really sure that we're importing from the local folder and not from another module with the same name located somewhere on path.

If you want to be able to start hdf5view from inside PyCharm, Spyder or another Python console, you could run it as a subprocess:

```python
import subprocess
a = subprocess.Popen("hdf5view")
````

Does that solve the issue for you?
